### ISSUE TITLE
Does not typecheck without hhvm/systemlib-extractor

### ISSUE THREAD

**Issue by kilahm** [fredemmott/definitions-finder#7]
Perhaps include an hhi in the source so the dev dependency doesn't break the type checker?

**Comment by fredemmott** [comment]
How are you installing this?

- if it's via composer and a tagged release, the tests/ directory should be excluded so this doesn't matter
- if you're cloning it, the require-dev dependencies should be pulled in automatically

**Comment by fredemmott** [comment]
(it shouldn't be an issue via composer because of https://github.com/fredemmott/definitions-finder/blob/master/.gitattributes )

**Comment by fredemmott** [comment]
HHI isn't a workable solution anyway, because when it the dependency is present that would be a duplicate definition.

**Comment by kilahm** [comment]
I was apparently running `--prefer-source` somewhere.  When I re-installed with `--prefer-dist` the tests folder was not included.

**Comment by fredemmott** [comment]
Ah, it sucks that prefer-source breaks this :( I don't know a better solution though.
